name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CMAKE_POLICY_VERSION_MINIMUM: 3.5

jobs:
  release-macos:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
      
      - name: Configure R2
        run: |
          mkdir -p ~/.config/rclone
          cat > ~/.config/rclone/rclone.conf <<EOF
          [r2]
          type = s3
          provider = Cloudflare
          access_key_id = ${{ secrets.ACCESS_KEY_ID }}
          secret_access_key = ${{ secrets.SECRET_ACCESS_KEY }}
          endpoint = https://b378d1f96efa355e3733177c37f0c9e7.eu.r2.cloudflarestorage.com
          EOF
      
      - name: Download game assets
        run: |
          rclone sync r2:gameformykids/resources/ resources/

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build \
            --target gameformykids \
            --config Release \
            --parallel 2

      - name: Install
        run: |
          cmake --install build \
            --prefix "${{ github.workspace }}/dist"

      - name: Package macOS app
        run: |
          ditto -c -k \
            --sequesterRsrc \
            --keepParent \
            "${{ github.workspace }}/dist/gameformykids.app" \
            "${{ github.workspace }}/gameformykids-${{ github.ref_name }}-macOS.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: gameformykids-${{ github.ref_name }}-macOS.zip
          generate_release_notes: true
